# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 005567ea8cf79645c6c6e9d42b5b0d1fc47309a2ea3d06a2a289b0d8fd42993f1e71740da7ec35ce07cf4940b8a5dda38a8ab1bfd8cb170c771e9c1bec0aa117

test:
  secret_key_base: 95c83b93385e5a6dee9b626d894cba789398f561c5b3c88f25123c8487ef93cf05acb857c802ef11f3ca25cb4239e73c3f8561daf8a86b6c616b9adbf3808130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
